-- ALittle Generate Lua
local ___thispath = select('1', ...):match("(.+[/\\]).+$") or ""
local ___pairs = pairs
local ___ipairs = ipairs


require(___thispath.."../../Core/Script/ALittle")
require(___thispath.."Std/Reflect/ReflectCmd")
require(___thispath.."Std/Reflect/ReflectCsv")
require(___thispath.."Std/Reflect/ReflectMessage")
require(___thispath.."Std/Loop/LoopObject")
require(___thispath.."Std/Loop/ILoopSystem")
require(___thispath.."Std/Loop/LoopFrame")
require(___thispath.."Std/Loop/LoopFunction")
require(___thispath.."Std/Loop/LoopGroup")
require(___thispath.."Std/Loop/LoopList")
require(___thispath.."Std/Loop/LoopTimer")
require(___thispath.."Std/Utility/Bit")
require(___thispath.."Std/Utility/WeakRef")
require(___thispath.."Std/Utility/IHeapTimer")
require(___thispath.."Std/Utility/ISchedule")
require(___thispath.."Std/Utility/CsvConfig")
require(___thispath.."Std/Utility/EventDispatcher")
require(___thispath.."Std/Utility/SafeIDCreator")
require(___thispath.."Std/Utility/String")
require(___thispath.."Std/Utility/File")
require(___thispath.."Std/Utility/JsonConfig")
require(___thispath.."Std/Net/HttpFileReceiverTemplate")
require(___thispath.."Std/Net/HttpFileSenderTemplate")
require(___thispath.."Std/Net/HttpReceiverTemplate")
require(___thispath.."Std/Net/HttpSenderTemplate")
require(___thispath.."Std/Net/MsgCommonTemplate")
require(___thispath.."Std/Net/MsgReceiverTemplate")
require(___thispath.."Std/Net/MsgSenderTemplate")
require(___thispath.."Std/Net/MsgSessionTemplate")
require(___thispath.."Adapter/Lua/LuaHeapTimer")
require(___thispath.."Adapter/Lua/LuaCsvFile")
require(___thispath.."Adapter/Lua/LuaHttpFileInterface")
require(___thispath.."Adapter/Lua/LuaHttpInterface")
require(___thispath.."Adapter/Lua/LuaMsgInterface")
require(___thispath.."Adapter/Lua/LuaMessageFactory")
require(___thispath.."Adapter/Lua/LuaSchedule")
require(___thispath.."Std/Loop/LoopSystem")
require(___thispath.."Std/Utility/Schedule")
