-- ALittle Generate Lua And Do Not Edit This Line!
do
if _G.ALittle == nil then _G.ALittle = {} end
local ALittle = ALittle
local Lua = Lua
local ___pairs = pairs
local ___ipairs = ipairs


ALittle.WebPermission = {
	PERMISSION_ACCOUNT_CREATE = "101",
	PERMISSION_ACCOUNT_DELETE = "102",
	PERMISSION_SET_ROLE = "103",
	PERMISSION_ACCOUNT_QUERY = "104",
	PERMISSION_ACCOUNT_LOGIN = "105",
	PERMISSION_SET_SELF_PWD = "106",
	PERMISSION_SET_ALL_PWD = "107",
	PERMISSION_ADD_RESOURCE = "108",
	PERMISSION_ROLE_CREATE = "201",
	PERMISSION_ROLE_UPDATE = "202",
	PERMISSION_ROLE_DELETE = "203",
	PERMISSION_ROLE_QUERY = "204",
	PERMISSION_PROGRESS_CREATE = "301",
	PERMISSION_PROGRESS_UPDATE = "302",
	PERMISSION_PROGRESS_DELETE = "303",
	PERMISSION_PROGRESS_QUERY = "304",
}

end