
#ifndef _ALITTLE_ROUTEDEFINE_H_
#define _ALITTLE_ROUTEDEFINE_H_

// #define CONNECT_INVOKE_LOG 1
// #define SEARCH_ROUTE_LOG 1
// #define CONNECT_ROUTE_LOG 1
// #define SESSION_ROUTE_LOG 1
// #define SESSION_INVOKE_LOG 1

#endif // _ALITTLE_ROUTEDEFINE_H_
